# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  repoName: 'janzi/vsts-build-agents'
  tagName: 'ubuntu-$(ubuntuversion)-docker-standard'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  displayName: Build docker standard image
  inputs:
    command: 'build'
    repository: '$(repoName)'
    Dockerfile: 'ubuntu/$(ubuntuversion)/docker/18.06.3-ce/standard/Dockerfile'
    tags: |
      $(Build.SourceBranchName)
      $(Build.BuildId)
      $(tagName)
    addPipelineData: true
    arguments: -t $(repoName):$(tagName)

- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: dockerhub

- task: Docker@1
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: dockerhub
    repository: '$(repoName)'
    includeSourceTags: true
    addDefaultLabels: true
    imageName: $(repoName):$(tagName)
    command: 'push'

- task: Docker@2
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: dockerhub

